### ISSUE TITLE
Add screen-sharing sound in dev/iOS-screen sharing branch

### ISSUE THREAD

**Issue by Apiphoom** [AgoraIO-Usecase/AgoraMeeting#11]
@plutoless @srs888001 @yoreland  did you have any plan for this? I am very interested.

**Comment by srs888001** [comment]
Sorry, there is no such plan at present.

**Comment by Apiphoom** [comment]
ohh.....

**Comment by Apiphoom** [comment]
@srs888001 I try to combine screen-sharing sound from Advance-video/repo, but when I combine it to agora-meeting I think I found a little problem the audio echo all the time when share-screen. Have any idea to solve this problem?

**Comment by Apiphoom** [comment]
@plutoless @yoreland any idea?

**Comment by srs888001** [comment]
Are you using the code from this link?
`https://github.com/AgoraIO/Advanced-Video/tree/master/iOS%26macOS/Agora-Screen-Sharing`

Do you have this problem when using this demo directly?

**Comment by Apiphoom** [comment]
I don't have any problem when use Advance-video screen sharing demo. But when I try to combine screen-sharing sound from Advance-video/repo, to agora-meeting I think I found a little problem the audio echo all the time when share-screen

**Comment by Apiphoom** [comment]
@srs888001 Any idea why it echo when I combine it in to Agora-Meeting?

**Comment by srs888001** [comment]
Maybe you can try to turn off the audio capture of Agora-Meeting when you turn on the screen sharing.

**Comment by Apiphoom** [comment]
@srs888001 How can I turn off the audio capture of Agora-Meeting? Can you guide me please?

**Comment by srs888001** [comment]
You can refer to : `https://github.com/AgoraIO-Usecase/AgoraMeeting/blob/master/AgoraMeeting_ iOS/VideoConference/Member/MemberVC.m#L140`

**Comment by Apiphoom** [comment]
THX! @srs888001

**Comment by Apiphoom** [comment]
Ahh I just tried it. It seems that it won't work. @srs888001

**Comment by Apiphoom** [comment]
@srs888001 can you provide some example code that can solve my echo problem please (:

**Comment by srs888001** [comment]
In fact, I am not sure why this problem occurred.
Let us communicate internally, and I will reply to you once there is a conclusion.

**Comment by Apiphoom** [comment]
@srs888001  Thank you!

**Comment by Apiphoom** [comment]
@srs888001 Have any new?

**Comment by yoreland** [comment]
The key difference here is Advanced-Video/tree/master/iOS%26macOS/Agora-Screen-Sharing is single process implement. All video/audio is published from ScreenShare extension.
But in agoraMeeting scenario. When you join channel from major process, VPIO session is enabled for conference call. In this case, it is problematic for screenshare extension is capture microphone and system audio. 

Above all, the solution for now is:
1. disable any audio sharing in screen sharing extension
2. microphone audio only sent from major process
3. if you also need publish media into channel, use startAudioMixing in major process

Let me know if above suggestion make sense for your requirement. :)

**Comment by Apiphoom** [comment]
Thank you very much @yoreland! but can you provide me an example for use "startAudioMixing" for publish audio sharing to channel?

**Comment by Apiphoom** [comment]
Or it possible to disable VPIO session?

**Comment by yoreland** [comment]
https://docs.agora.io/cn/Video/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/startAudioMixing:loopback:replace:cycle:

here it is the API for usage. You could also refer this demo:
https://github.com/AgoraIO/API-Examples/blob/master/iOS/APIExample/Examples/Advanced/AudioMixing/AudioMixing.swift

**Comment by Apiphoom** [comment]
Thank you very much! @yoreland if it work I will report you as soon as possible
