### ISSUE TITLE
Web demo 都跑不起来

### ISSUE THREAD

**Issue by chudongvip** [AgoraIO-Usecase/AgoraMeeting#13]
![image](https://user-images.githubusercontent.com/31001856/110065583-7376a600-7daa-11eb-9cda-1d89c556171d.png)

配置文件也配置了

![image](https://user-images.githubusercontent.com/31001856/110065631-90ab7480-7daa-11eb-9ae0-482749436472.png)

**Comment by plutoless** [comment]
@chudongvip 尝试一下删除node_modules/.cache
