### ISSUE TITLE
react app env values

### ISSUE THREAD

**Issue by vvks** [AgoraIO-Usecase/AgoraMeeting#4]
hi,

what are agora_endpoint_prefix that are to be updated in the env variable file

thnx

**Comment by srs888001** [comment]
I'm sorry about this. Maybe you can refer to the following settings:
`REACT_APP_AGORA_EDU_ENDPOINT_PREFIX=https://api.agora.io/scenario/meeting
REACT_APP_YOUR_BACKEND_WHITEBOARD_API=https://api.agora.io/scenario/meeting/apps/%app_id%/v1/room/%room_id%/board`

**Comment by vvks** [comment]
thnx. resolved
