### ISSUE TITLE
Terminating app due to uncaught exception

### ISSUE THREAD

**Issue by Apiphoom** [AgoraIO-Usecase/AgoraMeeting#8]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'room uuid 和 token 不能为空'
terminating with uncaught exception of type NSException

**Comment by Apiphoom** [comment]
@plutoless

**Comment by Apiphoom** [comment]
I don't known how to solve this problem ): Please help.

**Comment by Matrixbirds** [comment]
The reason in English is : `room uuid & token parameter cannot be empty`. Probably you passed the empty value for roomUuid and token, My suggestion is to check the parameter in your environment.

**Comment by Apiphoom** [comment]
I use the AgoraMeeting sample and it give me that error and I don't know how to solve it (I'm not good at OBJ-C. I only got at swift sorry for that ;-;)

**Comment by Apiphoom** [comment]
@Matrixbirds Thank you very much!!!!! NoW I solve the issue. I update some code and framework and it work for me.
I think I have to learn Chinese to understand the error haha.
